---
title: "President"
---

<br><br><br><br><br><br>
# President
The President represents all YCA students to the administration and PKU, and coordinates GSU events and activities.

## 2019 Candidates

### Yoneda Akihiro -- 5th cohort
"Dear YCA family, my name is Yoneda Akihiro, and I am willing to dedicate time and energy to serving you as a President of YCA. The moment I immersed myself into this community, I fell in love with Yenching spirit, got stricken by its diversity that I can listen to, appreciate and relate to, got addicted to listening to the life stories, ideas and voices. I felt an urge to present myself to this vibrant community as a servant, as a friend and as an advocator.

First, I am a Chinese native speaker, which will allow me to fluently deliver our messages and return the feedback from outside. Second, as an international student, 7 years of life in Chinese high school and university helped me to build a bridge between the global mindset and the culture of China. Third, I am a competition-driven person. Having been a team captain back in school and university, I remember the spirit of leading the team towards victory and recognition. As a leader, I can be a good listener and collaborative coordinator with my teammates, making sure we are serving the clear goal all together.

And last, being a president of YCA, I will listen to everyone’s point of view and deliver a clear message to the outer community with my deep understanding of China, value of our goals and care for every single one in YCA."
<br><br>


### Jun-Hyuk Lee (Michael) -- 4th cohort
“As a student counsellor and proctor in school and a mentor in university, my peers have always been my top priority. The next GSU President will represent students at the table with the administration, but it should also work to better serve scholars in their aspirations whilst in China. With Kenneth He as my running mate, I envision that GSU 2019-2020 will be above all a team effort.

Being a second-year YCA office assistant and having completed coursework, I am experienced and equipped to promote student interests. I am committed to leaving a structural legacy behind at YCA. I would create an alumni network for current students seeking career advice, a housing directory for scholars staying on for the second year, and negotiate a discount plan for scholars going to United Family hospitals.

To foster inter-communal ties within YCA and the rest of PKU, the GSU would host more inter-PKU mixer events, institute Chinese-language happy hours, and make events such as the Winter Ball ticketed to expand accessibility and the availability of funds. The GSU will also organise volunteer trips during the vacations and on weekends, on top of the community happy hours it has led before.

I also want to make guidelines on academics and extracurriculars at YCA more transparent. I would streamline orientation, clarify the criteria for clubs and funding, and revamp the extracurricular point system. Furthermore, I would negotiate enlargement of popular spring term courses and more continuous feedback from professors.

*__If it’s Mike Lee, It’s Likely!”__*
<br><br>


### Si Peng Xie (Gary) -- 5th cohort

“You applied to YCA with some goals in mind.

GSU’s sole purpose should be to help you achieve those goals.

Maybe you came for PKU. Then you should have the chance to build your PKU connection and use its resources. As GSU president, I will bring students from other PKU departments to YCA and have academic discussions, networking events, language salons and social gatherings with them. GSU would give me the resources to speak to student organizations from other departments and make this happen.

Maybe you came for the amazing YCA scholars. Do you feel like you are able to engage with everyone from different backgrounds without impediment? As GSU president, I will organize events to bring Chinese scholars and foreign scholars to mingle more. I will also raise school spirits by ordering fashionable YCA clothing. GSU gives me the platform to push for a better experience for you.

Maybe you came for the program. Do you feel like you have a good grasp of what is going on? How much do you know about academic writing class schedules and how many days in advance did you know about networking events? As GSU president I will push for transparency and facilitate more information sharing, thru a weekly newsletter. 

Who do you trust to talk to YCA office and other PKU departments?

As a native Chinese and English speaker, who studied in multiple school systems, I am the one you can trust to defend your interests diplomatically at PKU.”
<br><br>


### Vijaya Lakshmi Iyengar -- 5th cohort

“Yenching Academy is a rare community filled with diverse people. Because of our differences in background and interests, we have so much to share with one another. Yet, because of these same differences, our methods of doing so may differ. This is true amongst current YCA scholars, YCA scholars and PKU students, and current YCA scholars, prospective scholars, and alumni. As president of the Graduate Students Union I want to connect Yenching into one big family, because our best resources are each other. This goal is multilateral and requires help from every sector of the GSU, from public relations to events. Specifically, it requires initiates such as outreach from the public relations group to various universities to allow for onsite alumni orientations about Yenching. It requires aid from director of Academic Affairs to help arrange self-talks, or small talks given by our own scholars about issues they’re passionate about and encourage moderated discussion afterwards. It needs the support of the Director of Operations to help us set up a system where alums update what they’re doing with contact information, so students can reach out for help. It requires help from the director of events to help pair us with PKU clubs to hold biweekly events where 10 YCA and 10 PKU students come together and play games, talk, and share each other’s company. All of these initiatives can shape the Yenching experience for years to come. As president of the GSU, I will be committed to this vision of a connected Yenching Academy.”
<br><br>


### Jonah Lefkoe -- 5th cohort

“Listening has been the most meaningful work of my life. As a peer mental health counsellor during college, I witnessed the power of listening and how small groups can build trust together. When classmates of any identity or national origin, holding any experience came to talk with our organization, we were ready to listen and to serve. 

I am running for YCA GSU President because I believe in that model of compassionate leadership for YCA. 

This campaign is built on three goals: committing to service, building dialogue, and strengthening our futures. 

We believe that direct community service is one of the best ways that YCA can foster intercultural understanding, which is why we propose a YCA Community Service Fellowship to place interested students in Beijing service organizations. 

We propose new programs that use small outing groups to unite classmates with common interests. We will also work with the Office to clarify the club renewal process, ensuring that everyone receives structural representation and support at YCA. 

We will expand the YCA career advising network by gathering data on our goals, creating an alumni database, and connecting students with mentors across graduate schools, industries, and organizations. 

In this campaign, I am lucky to be united with Derek Zeng, candidate for vice president and experienced student leader who serves as a liaison between YCA and the broader PKU community. 

If you share our vision of committing to service, building dialogue, and strengthening our futures, let’s talk. We can’t wait to listen and serve YCA together.”
<br><br>